[package]
name = "raytrace"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
lodepng = "2.5.0"

[profile.release]
debug = true
